title:            Written Rhetoric
description:      musings of a writing traveler.
brief:            "a collection of haphazard sagas collected alongside twisted and strange commentary that varies in nature, humor and darkness."

# The site's domain - when testing locally leave blank or use http://localhost:4000
url: http://writtenrhetoric.com
baseurl: "" # the subpath of the site, e.g. /blog/

#disqus_shortname: writingtraveler
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/bg_ink.png

# draw the top menu here - each item must have a title and a url (o list post categories. use type: 'categories')
menu:
  - title: 'Stories'
    url: '/pages/stories'
  - title: 'Browse'
    url: '#'
    submenu:
    - title: 'Categories'
      url: '/categories'
      type: 'categories'
    - title: 'Tags'
      url: '/tags'
      type: 'tags'
    - title: 'Archive'
      url: '/pages/archive'
    - title: 'About'
      url: '/pages/about'

# Owner/author information
owner:
  name:           Pedro Ávila
  email:          writingtraveler@gmail.com
  site:           http://about.me/pedroavila
  # Twitter nick for use in Twitter cards and follow button.
  #twitter: birdular # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  #github: narcan

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "facebook"
    url: "https://facebook.com/writtenrhetoric"
  - title: "google plus"
    url: "https://plus.google.com/communities/110598470354803114281"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone:    America/New_York
timezone:    TIMEZONE
locale:      en_US
future:      true
markdown:    kramdown
#highlighter: pygments
plugins: [
  jekyll-sitemap,
  jekyll-paginate
]
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title/

# Amount of post to show on home page
#paginate_path: "/blog/page:num/"
paginate: 10

# if true, shows the floating share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: coderay

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]